---
# tasks file for simon/k8s/roles/k8s_fundamentals
- name: Disable swap
  ansible.builtin.include_tasks: disable_swap.yml

- name: Increase disk space
  ansible.builtin.include_tasks: increase_disk.yml

- name: Install k8s dependencies
  ansible.builtin.include_tasks: install_k8s_deps.yml

- name: Prepare network
  ansible.builtin.include_tasks: prepare_network.yml

- name: Install containerd
  ansible.builtin.include_tasks: install_containerd.yml

- name: Install k8s
  ansible.builtin.include_tasks: install_k8s.yml
