---
- name: Disable SWAP since kubernetes can't work with swap enabled
  notify: Delete swap from fstab
  ansible.builtin.shell:
    cmd: swapoff -a && touch /root/.swapoff
    creates: /root/.swapoff
